name: yuu2dev
description: 풀스택을 위한 기술 블로그 입니다
meta_description: ""

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: "http://yuu2dev.github.io"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "yuu2dev"
# Disqus config
disqus-shortname: ""
